pull_request_rules:
  - name: automatic merge for PyUp pull requests
    conditions:
      - author=pyup-bot
      - status-success=Travis CI - Pull Request
    actions:
      merge:
        method: merge
